### PR TITLE
converted to gomod, pinned x/tools

### PR DESCRIPTION
**Pull request by morganhein**
This is my first time using go mod. Thought this was low enough hanging fruit to tackle, and seems to work fine once compiled, however doesn't seem to work when using `go run main.go`.

LMK if there's any amiss.

Cheers.

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
@morganhein you will need to execute `go run *.go`, since there is several go files.

**Comment by jvrplmlmn** [comment]
@davecheney any chance you could review this? 🙏

**Comment by morganhein** [comment]
> @morganhein you will need to execute `go run *.go`, since there is several go files.

Ah, awesome, ty.

**Comment by rjeczalik** [comment]
Currently `go get github.com/davecheney/godoc2md` fails on master with:

```
# github.com/davecheney/godoc2md
../../davecheney/godoc2md/main.go:173:6: pres.ShowExamples undefined (type *godoc.Presentation has no field or method ShowExamples)
../../davecheney/godoc2md/main.go:184:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
../../davecheney/godoc2md/main.go:186:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
../../davecheney/godoc2md/main.go:189:12: undefined: godoc.CommandLine
```

This PR fixes it, just fyi.

**Comment by rjeczalik** [comment]
@reallyroy Most likely you have cached old version locally on your disk - does `go get -u github.com/davecheney/godoc2md` work?

**Comment by reallyroy** [comment]
Still seeing the same error.
```bash
$ go get -u github.com/davecheney/godoc2md
# github.com/davecheney/godoc2md
../../workspaces/go/src/github.com/davecheney/godoc2md/main.go:173:6: pres.ShowExamples undefined (type *godoc.Presentation has no field or method ShowExamples)
../../workspaces/go/src/github.com/davecheney/godoc2md/main.go:184:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
../../workspaces/go/src/github.com/davecheney/godoc2md/main.go:186:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
```

**Comment by rjeczalik** [comment]
@reallyroy apparently you may want to switch over to go1.11

**Comment by montanaflynn** [comment]
@rjeczalik I'm also getting the same error on go1.11:

```
go version go1.11 darwin/amd64
go get -u github.com/davecheney/godoc2md
# github.com/davecheney/godoc2md
../../davecheney/godoc2md/main.go:173:6: pres.ShowExamples undefined (type *godoc.Presentation has no field or method ShowExamples)
../../davecheney/godoc2md/main.go:184:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
../../davecheney/godoc2md/main.go:186:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
```

**Comment by timbunce** [comment]
go version go1.11.2 darwin/amd64
go version go1.11.5 darwin/amd64
both report:
```
go get -u github.com/davecheney/godoc2md
go: finding github.com/davecheney/godoc2md latest
go: finding golang.org/x/tools latest
# github.com/davecheney/godoc2md
../../../../pkg/mod/github.com/davecheney/godoc2md@v0.0.0-20190102190552-ec8f0aeaa913/main.go:173:6: pres.ShowExamples undefined (type *godoc.Presentation has no field or method ShowExamples)
../../../../pkg/mod/github.com/davecheney/godoc2md@v0.0.0-20190102190552-ec8f0aeaa913/main.go:184:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
../../../../pkg/mod/github.com/davecheney/godoc2md@v0.0.0-20190102190552-ec8f0aeaa913/main.go:186:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
../../../../pkg/mod/github.com/davecheney/godoc2md@v0.0.0-20190102190552-ec8f0aeaa913/main.go:189:12: undefined: godoc.CommandLine
```

**Comment by morganhein** [comment]
@timbunce I feel like this line: ```go: finding golang.org/x/tools latest``` indicates it's ignoring the go mod files. It *should not* be downloading the latest golang tools, since it's supposed to be pinned. 

If you do a ```go mod vendor``` inside the gomod2doc folder, and inspect the golang.org/x/tools dep, you should see the ```godoc.CommandLine``` function, for example. If it's not, then it's ignoring the mod.

**Pull request merged**
